### Biblioteca Numpy (numerical python):</H1>
https://numpy.org/

#### Para instalar o numpy digite no terminal:
pip install numpy

In [1]:
#importando a biblioteca (lib) numpy
import numpy as np #np é um apelido para facilitar a nossa chamada a lib

In [24]:
numeros = np.array([6,12,6,7,8,1,0,3,5,106], dtype='i')

numeros

array([  6,  12,   6,   7,   8,   1,   0,   3,   5, 106], dtype=int32)

In [17]:
print(numeros[6] == numeros[7])

False


In [10]:
#descobrindo o tipo de dado do array
print(type(numeros))

<class 'numpy.ndarray'>


In [11]:
#descobrindo o tipo dos dados
print(numeros.dtype)

int32


In [18]:
#imprimindo o numero de dimensoes de um array
print(numeros.ndim)

1


In [19]:
#tamanho do array
print(numeros.shape)

(10,)


In [21]:
print(len(numeros))

10


In [20]:
#numero de elementos de um array
print(numeros.size)

10


In [25]:
#imprimindo um array para ver o conteúdo
print(numeros)

[  6  12   6   7   8   1   0   3   5 106]


In [23]:
#acessando elementos individuais de um array
print(numeros[0])# primeira posicao do array
print(numeros[1])# segunda posicao do array
print(numeros[4])
print(numeros[9])#ultimo elemento é sempre n-1
print(numeros[-1]) #ultima posicao do array
print(numeros[-2]) #penúltima posicao do array
print(numeros[-3]) #antepenúltima posicao do array


6
12
8
106
106
5
3


In [26]:
#fazendo alteracoes no vetor
numeros[0] = 3
print(numeros[0])

3


<H1>Peenchendo arrays com valores específicos</H1>

In [27]:
# lista = []
# for n in range(0, 101, 2):
#     lista.append(n)
# pares = np.array(lista)
#criar um array com numeros pares de 0 a 100
pares = np.array([n for n in range(0, 101,2)])
print(pares)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [32]:
#cria um array com 10 elementos iguais a zero
print(np.zeros(10)) 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [28]:
#cria um array com 15 elementos iguais a um
print(np.ones(15))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [29]:
#criar array com 8 posicoes iguais a 12 (int)
#primeiro argumento: num de elementos
#segundo argumento: o valor que ira preencher em cada posicao do array
print(np.full(8, 12))

[12 12 12 12 12 12 12 12]


In [37]:
#Podemos especificar o tipo de dados dos elementos
print(np.zeros(10, dtype = int)) 
print(np.ones(15, dtype = int))
print(np.full(8, 12, dtype = float))

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[12. 12. 12. 12. 12. 12. 12. 12.]


<H1>Criar array a partir de faixas de valores</H1>

In [31]:
print(np.arange(10))#array de 10 elementos, numeros de 0 a 9
print(np.arange(10.))#array de 10 elementos float, numeros de 0 a 9
print(np.arange(5,16))#array com valores no intervalo de 5 a 15
print(np.arange(50, 1, -2))#array com os numeros pares de 50 ate 1

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 5  6  7  8  9 10 11 12 13 14 15]
[50 48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10  8  6  4
  2]


In [38]:
from random import randint
teste = randint(1, 100)
print(teste)

25


In [40]:
#criar e preencher array com valores aleatorios
a = np.random.randint(1, 100, size=10)
print(a)

[24 35 73 37  7 94 51 94 17 87]


In [50]:
#Gera um numero aleatorio entre 0 e 8
print(f'Número sorteado: {np.random.randint(9)}')

Número sorteado: 7


In [41]:
#Gera 10 numeros aleatorios inteiros entre 10 e 20
b = np.random.randint(10, 20, size=10)
print(b)

[15 16 16 17 12 10 15 16 16 16]


<H1>Um pouco de estatistica ....</H1>

In [61]:
print(f'Média de b: {np.mean(b)}')#calculo da media artimetica
print(f'Mediana de b: {np.median(b)}')#calculo da mediana
print(f'Menor valor de b: {np.min(b)}')
print(f'Maior valor de b: {np.max(b)}')
print('------------------')
print(f'Somatoria de b: {np.sum(b)}')

Média de b: 16.0
Mediana de b: 18.0
Menor valor de b: 10
Maior valor de b: 19
------------------
Somatoria de b: 160


In [44]:
mult_matrizes = np.dot(a,b)
print(a)
print(b)
print(mult_matrizes)

[24 35 73 37  7 94 51 94 17 87]
[15 16 16 17 12 10 15 16 16 16]
7674


In [45]:
p = [[1,2],
     [2,3]]

q = [[4,5],
     [6,7]]

result = np.dot(p,q)
np.linalg.det(p)
print(result)

[[16 19]
 [26 31]]
