<H1>Biblioteca Numpy (numerical python):</H1>
https://numpy.org/

<h1>Para instalar o numpy digite no terminal:</h1>
pip install numpy

In [4]:
#importando a biblioteca (lib) numpy
import numpy as np #np é um apelido para facilitar a nossa chamada a lib

In [66]:
numeros = np.array([6,12,6,7,8,1,0,3,5,16], np.int16)

numeros

array([ 6, 12,  6,  7,  8,  1,  0,  3,  5, 16], dtype=int16)

In [68]:
#descobrindo o tipo de dado do array
print(type(numeros))

<class 'bool'>
<class 'numpy.ndarray'>


In [67]:
#descobrindo o tipo dos dados
print(numeros.dtype)

int16


In [69]:
#imprimindo o numero de dimensoes de um array
print(numeros.ndim)

1


In [27]:
#tamanho do array
print(numeros.shape)

(10,)


In [70]:
#numero de elementos de um array
print(numeros.size)

10


In [84]:
#imprimindo um array para ver o conteúdo
print(numeros)

[ 3 12  6  7  8  1  0  3  5 16]


In [112]:
for i in range(0, numeros.size):#[0 até 10[ : 0,1,2,3,4,5,6,7,8,9
    print(f'posicao {i}: {numeros[i]}')

posicao 0: 9
posicao 1: 12
posicao 2: 6
posicao 3: 7
posicao 4: 8
posicao 5: 1
posicao 6: 0
posicao 7: 3
posicao 8: 5
posicao 9: 16


In [105]:
#acessando elementos individuais de um array
print(numeros[0])# primeira posicao do array
print(numeros[1])# segunda posicao do array
print(numeros[4])
print(numeros[-1]) #ultima posicao do array
print(numeros[-2]) #penúltima posicao do array
print(numeros[-3]) #antepenúltima posicao do array
print(numeros[-8])


9
12
8
16
5
3
6


In [104]:
#fazendo alteracoes no vetor
numeros[0] = 9
print(numeros[0])

9


In [115]:
#converteu o array em lista e imprimiu invertido
lista_ = list(reversed(numeros))
print(type(lista_))
print(lista_)

<class 'list'>
[16, 5, 3, 0, 1, 8, 7, 6, 12, 9]


<H1>Peenchendo arrays com valores específicos</H1>

In [116]:
#criar um array com numeros pares de 0 a 100
pares = np.array([n for n in range(0, 101,2)])
print(pares)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [117]:
#cria um array com 10 elementos iguais a zero
print(np.zeros(10)) 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [89]:
#cria um array com 15 elementos iguais a um
print(np.ones(15))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [118]:
#criar array com 8 posicoes iguais a 12 (int)
#primeiro argumento: num de elementos
#segundo argumento: o valor que ira preencher em cada posicao do array
print(np.full(8, 12))

[12 12 12 12 12 12 12 12]


In [121]:
#Podemos especificar o tipo de dados dos elementos
print(np.zeros(10, dtype = int)) 
print(np.ones(15, dtype = str))
print(np.full(8, 12, dtype = float))

[0 0 0 0 0 0 0 0 0 0]
['1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1' '1']
[12. 12. 12. 12. 12. 12. 12. 12.]


<H1>Criar array a partir de faixas de valores</H1>

In [157]:
print(np.arange(10))#array de 10 elementos, numeros de 0 a 9
print(np.arange(10.))#array de 10 elementos float, numeros de 0 a 9
print(np.arange(5,16))#array com valores no intervalo de 5 a 15
print(np.arange(50, 1, -2))#array com os numeros pares de 50 ate 1
print(np.arange(numeros.size, 0, -1))

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 5  6  7  8  9 10 11 12 13 14 15]
[50 48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10  8  6  4
  2]
[10  9  8  7  6  5  4  3  2  1]


In [93]:
#criar e preencher array com valores aleatorios
a = np.random.rand(10)
print(a)

[0.78535827 0.82372174 0.33545729 0.30774186 0.34367042 0.28321228
 0.04635304 0.25621434 0.78532412 0.22029195]


In [156]:
#Gera um numero aleatorio entre 0 e 8
print(f'Número sorteado: {np.random.randint(9)}')

Número sorteado: 6


In [158]:
#Gera 10 numeros aleatorios inteiros entre 10 e 20
b = np.random.randint(10, 20, size=10)
print(b)

[19 13 12 11 11 15 10 10 11 14]


<H1>Um pouco de estatistica ....</H1>

In [159]:
print(f'Média de b: {np.mean(b)}')#calculo da media artimetica
print(f'Mediana de b: {np.median(b)}')#calculo da mediana
print(f'Menor valor de b: {np.min(b)}')
print(f'Maior valor de b: {np.max(b)}')
print('------------------')
print(f'Somatoria de b: {np.sum(b)}')

Média de b: 12.6
Mediana de b: 11.5
Menor valor de b: 10
Maior valor de b: 19
------------------
Somatoria de b: 126


In [6]:
a = np.array(['', '', ''], dtype=object)
print(a)


for i in range(0, len(a)):
    a[i] = input('Qual seu nome?')

print(a)

['' '' '']
['Anderson' 'João' 'Maria']
