## Estudando Matrizes em Python com Numpy

In [23]:
## Instalar a lib numpy

#pip install numpy

In [1]:
import numpy as np

In [25]:
# Criando uma matriz de 3 linhas e 3 colunas
m = np.array([
              [1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]
              ])
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
#Acessando o valor de um indice
print(m[1,1])

5


In [28]:
# Alterando o valor de um indice
m[0,1] = 7

In [29]:
print(m)

[[1 7 3]
 [4 5 6]
 [7 8 9]]


In [30]:
#visualizar uma coluna especifica (Use o fatiamento - slicing)
print('Primeira coluna:', m[:,0])
print('Segunda coluna:', m[:,1])
print('Terceira coluna:', m[:,2])

Primeira coluna: [1 4 7]
Segunda coluna: [7 5 8]
Terceira coluna: [3 6 9]


In [31]:
print('Toda matriz:\n', m[:])

Toda matriz:
 [[1 7 3]
 [4 5 6]
 [7 8 9]]


In [32]:
# visualizar uma linha especifica (Use o fatiamento - slicing)
print('Primeira linha:', m[0,:])
print('Segunda linha:', m[1,:])
print('Terceira linha:', m[2,:])

Primeira linha: [1 7 3]
Segunda linha: [4 5 6]
Terceira linha: [7 8 9]


In [19]:
#numero de dimensoes
print(m.ndim)

2


In [20]:
#tamanho da matriz - ordem da matriz
print(m.shape)

(3, 3)


In [21]:
#numero de elementos de uma matriz
print(m.size)

9


In [35]:
nova_matriz = np.zeros((3,4), dtype = int)
nova_matriz

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [36]:
matriz_um = np.ones((2,2), dtype= int)
matriz_um

array([[1, 1],
       [1, 1]])

In [38]:
len(nova_matriz)

3