In [2]:
import numpy as np

matriz = np.random.rand(3,6)

soma_vendas = 0
soma_vendedor = 0
valor_vendedor_top = 0
vendedor_top = ""

for i in range(0, len(matriz)):
    soma_vendedor += soma_vendedor

    if soma_vendedor >= valor_vendedor_top:
        vendedor_top = f"Vendedor  {i+1}"
        
    for j in range(0, len(matriz[0])):
        soma_vendas += matriz[i][j]

print(np.round(matriz,2))
print('Soma de vendas: {:.2f}'.format(soma_vendas))
print(f'Vendedor top: {vendedor_top}')

[[0.88 0.76 0.31 0.64 0.29 0.81]
 [0.28 0.89 0.2  0.85 0.54 0.22]
 [0.14 0.59 0.59 0.31 0.59 0.36]]
Soma de vendas: 9.27
Vendedor top: Vendedor  3
